//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_Stage_Applicatie.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Login
    {
        [Required]
        public string Gebruikersnaam { get; set; }
        [Required]
        public string Wachtwoord { get; set; }
        public int Persoonsgegevens { get; set; }
    
        public virtual Persoonsgegevens Persoonsgegevens1 { get; set; }
    }
}
