//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_Stage_Applicatie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Persoonsgegevens = new HashSet<Persoonsgegevens>();
        }
    
        public int RolID { get; set; }
        public string RolNaam { get; set; }
    
        public virtual ICollection<Persoonsgegevens> Persoonsgegevens { get; set; }
    }
}
