//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_Stage_Applicatie.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TussentijdseBeindeging
    {
        public TussentijdseBeindeging()
        {
            this.RedenOnderwijsinstelling = new HashSet<RedenOnderwijsinstelling>();
            this.RedenOrganisatie = new HashSet<RedenOrganisatie>();
            this.RedenStudent = new HashSet<RedenStudent>();
        }
    
        public int TussentijdsebeoordelingID { get; set; }
        public int Stage { get; set; }

        [Required(ErrorMessage = "Beoogde einddatum is een verplicht veld")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime Einddatum { get; set; }

        [RegularExpression(@"[0-9]{5}", ErrorMessage = "Een CREBO nummer is 5 cijfers")]
        [Required(ErrorMessage = "CREBO is een verplicht veld")]
        public string CREBO { get; set; }

        [Required(ErrorMessage = "Leerweg is een verplicht veld")]
        public int Leerweg { get; set; }
    
        public virtual Stage Stage1 { get; set; }
        public virtual ICollection<RedenOnderwijsinstelling> RedenOnderwijsinstelling { get; set; }
        public virtual ICollection<RedenOrganisatie> RedenOrganisatie { get; set; }
        public virtual ICollection<RedenStudent> RedenStudent { get; set; }
    }
}
